name: Build AverageTerrariaSurvival
'on':
  - push
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ['6.0']
    steps:
    - uses: actions/checkout@v3
    - name: Directorize
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '${{ matrix.dotnet-version }}'
    - name: SimpleEcon
      run: dotnet add package SimpleEcon -s "C:\Users\Julian\Documents\GitHub\SimpleEcon\SimpleEcon\bin\Debug\net6.0\SimpleEcon.dll"
    - name: Install Dependencies
      run: dotnet restore
    - name: Go to directory
      run: 'cd "C:\Users\Julian\Documents\GitHub\AverageTerrariaMain"'
    - name: Build
      run: dotnet build
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: AverageTerrariaSurvival latest
        path: avs-latest
      if: '${{ always() }}'
